[package]
name = "cashu-rs-mint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
axum = "0.6.18"
axum-macros = "0.3.7"
cashu = { path = "../cashu-rs" }
cln-rpc = "0.1.3"
config = { version = "0.13.3", features = ["toml"] }
dirs = "5.0.1"
futures = "0.3.28"
log = "0.4.19"
redb = "0.22.0"
serde = "1.0.164"
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread", "sync"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
uuid = { version = "1.3.4", features= ["v4","fast-rng"] }
