[workspace]

members = [
    "mint",
    "types",
    "mint-manager"
]

[workspace.metadata]
authors = ["thesimplekid"]
edition = "2021"
description = "cashu-rs-mint"
readme = "README.md"
repository = "https://github.com/thesimplekid/cashu-rs-mint"
license-file = "LICENSE"
keywords = ["bitcoin", "e-cash", "cashu"]
