[info]
url = "https://example.com/"
listen_host = "127.0.0.1"
listen_port = 8085
mnemonic = "inner strategy nasty verify camp bind avoid cause glue holiday dress bounce exotic husband hungry winter diet town spray team number hen upper seek"
max_order = 32
db_path = "./mint.redb"

#[mint_info]
#name = "test mint"
#description = "A mint for testing"
#description_long = "A longer mint for testing"
#motd = "Hello world"

[contact]
email = "me@example.com"

[ln]

# Required ln backend `Cln`, `Ldk`, `Greenlight`
ln_backend = "Cln"

# CLN
cln_path = "/home/thesimplekid/Documents/Development/cashu-rs-mint/tmp/ln_1/regtest/lightning-rpc"

# Required to start greenlight for the first time
# greenlight_invite_code = ""

fee_percent = 1.0
reserve_fee_min = 1000

[node_manager]
enable_node_manager = true
authorized_users = ["04918dfc36c93e7db6cc0d60f37e1522f1c36b64d3f4b424c532d7c595febbc5"]
jwt_secret = "supersecretprivatekey"
listen_host = "127.0.0.1"
listen_port = 8086
