[info]
url = "https://example.com/"
listen_host = "127.0.0.1"
listen_port = 8085
secret_key = "supersecretprivatekey"
max_order = 32

[mint_info]
name = "test mint"
description = "A mint for testing"
motd = "Hello world"

[contact]
email = "me@example.com"

[ln]
cln_path = "~/.lightning/signet/lightning-rpc"
authorized_users = ["04918dfc36c93e7db6cc0d60f37e1522f1c36b64d3f4b424c532d7c595febbc5"]
enable_node_manager = false
jwt_secret = "supersecretprivatekey"
ln_backend = "Cln"
fee_percent = 1.0
reserve_fee_min = 1000